---
- name: Create metallb definition files folder
  file:
    path: /opt/k8s/metallb
    state: directory
    owner: localadmin
    group: localadmin
    mode: '0644'

- name: Copy monitoring ingress definition file to target machine
  copy:
    src: ./metallb/configs/
    dest: /opt/k8s/metallb/
    owner: localadmin
    group: localadmin
    mode: '0644'

- name: Set up metallb namespace
  shell: kubectl apply -f /opt/k8s/metallb/namespace.yaml  
  register: metallb_namespace_result
  changed_when: '"created" in metallb_namespace_result.stdout'
  become: yes

# - name: Set up metallb objects
#   shell: kubectl apply -f /opt/k8s/metallb/metallb.yaml
#   register: metallb_objects_result
#   changed_when: '"created" in metallb_objects_result.stdout'
#   become: yes

- name: Create metallb generic secrets
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  register: metallb_secret_result
  changed_when: '"created" in metallb_secret_result.stdout'
  become: yes

- name: Set up metallb configmap
  shell: kubectl apply -f /opt/k8s/metallb/configmap.yaml
  register: metallb_configmap_result
  changed_when: '"created" in metallb_configmap_result.stdout'
  become: yes
  