---
# - name: Update apt cache
#   yum:
#     update_cache: yes
#     update_cache_retry_max_delay: 12

- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ extra_packages }}"
  when: extra_packages | default([]) | length > 0

# commenting this out because it was previously required to upgrade python in order to execute kubernetes modules
# - name: Setup python3.9
#   include_tasks: ./setup-python.yaml
  