---
- name: Ensure older versions of Docker are not installed
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd.io
      - runc
    state: absent

# this is for determining which docker packages to install x86_64, armhf, arm64
- name: Get machine architecture
  script: "./scripts/get-architecture.py {{ ansible_architecture }}" 
  args:
    executable: python3
  register: get_machine_arch_result

- name: Set machine architect fact
  set_fact:
    machine_architecture: "{{ get_machine_arch_result.stdout | trim | default('amd64', true) }}"

- name: Update apt package index
  yum:
    update_cache: yes

- name: Install required packages for using docker repository over HTTPS
  yum:
    name:
    - chrony
    - ca-certificates
    - curl
    - gnupg2
    state: present
  
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker engine
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Copy docker daemon.json for specifying systemd as cgroup driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Add docker user
  user:
    name: localadmin
    groups: docker
    append: yes

- name: Restart docker
  service:
    name: docker
    state: restarted