---
- name: Register kubernetes version
  shell: kubectl version | base64 | tr -d '\n'
  register: kubectl_version

- name: Install Weave
  command: "kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml"
  register: weave_result
  changed_when: "'created' in weave_result.stdout"