---
- name: Install Flannel
  become: yes
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"

# - name: install Pod network
#   become: yes
#   become_user: localadmin

  # shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
  # args:
  #   chdir: $HOME
  #   creates: pod_network_setup.txt
  # register: flannel_result
  # changed_when: "'created' in flannel_result.stdout"

